networks:
  otel_network:

services:
  app:
    build: .
    container_name: express_otel_app
    environment:
      - OTLP_TRACE_URL=http://otel-collector:4318/v1/traces
      - OTLP_METRIC_URL=http://otel-collector:4318/v1/metrics
      - OTLP_LOGS_URL=http://otel-collector:4318/v1/logs
      - OTEL_RESOURCE_ATTRIBUTES=service.name=mock-express-app
      - OTEL_SERVICE_NAME=mock-express-app
      - NODE_ENV=production
    volumes:
      - /var/log:/var/log   # 👈 Share logs with Promtail
    ports:
      - "3000:3000"
    depends_on:
      - otel-collector
    networks:
      - otel_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.90.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml
    command: ["--config=/etc/otel/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    environment:
      - OTEL_LOG_LEVEL=debug
    networks:
      - otel_network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - otel_network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - otel_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel_network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3001:3000"
    networks:
      - otel_network
